name: Deploy Flask Backend to AWS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt
          python -m venv venv
          source venv/bin/activate

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # Replace with your AWS region

      - name: Install Elastic Beanstalk CLI
        run: |
          pip install awsebcli

      - name: Initialize Elastic Beanstalk
        run: |
          eb init -p python-3.10 NoteCardsApp --region us-west-2 # Replace with your app name and region
          eb use NoteCardsApp-env # Replace with your environment name

      - name: Deploy to AWS Elastic Beanstalk
        run: |
          eb deploy