name: CI/CD Pipeline - Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master  # Replace with the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip python3-dev build-essential
        pip3 install awsebcli

    - name: Deploy to Elastic Beanstalk
      run: |
        # Initialize Elastic Beanstalk app
        eb init -p python-3.10 --region ${{ secrets.AWS_REGION }} --no-verify-ssl
        eb use ${{ secrets.EB_ENV_NAME }}  # Specify the Elastic Beanstalk environment
        eb deploy