name: CI/CD Pipeline - Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master  # Replace with the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip python3-dev build-essential
        pip3 install awsebcli

    - name: Deploy to Elastic Beanstalk
      run: |
        # Create a version name with timestamp
        VERSION_NAME="app-$(date +'%Y%m%d%H%M%S')"
        echo "Creating application version: $VERSION_NAME"
        
        # Initialize EB CLI
        eb init ${{ secrets.EB_APP_NAME }} -p python-3.11 --region ${{ secrets.AWS_REGION }}
        
        # Check if environment exists
        ENV_EXISTS=$(aws elasticbeanstalk describe-environments --region ${{ secrets.AWS_REGION }} --application-name ${{ secrets.EB_APP_NAME }} --query "Environments[?EnvironmentName=='${{ secrets.EB_ENV_NAME }}'].EnvironmentName" --output text)
        
        if [ "$ENV_EXISTS" == "" ]; then
          echo "Environment doesn't exist. Creating a new environment..."
          eb create ${{ secrets.EB_ENV_NAME }} --region ${{ secrets.AWS_REGION }}
        else
          echo "Environment exists. Deploying to existing environment..."
          eb use ${{ secrets.EB_ENV_NAME }}
        fi
        
        # Package application
        zip -r ${VERSION_NAME}.zip .
        
        # Upload to S3
        aws s3 cp ${VERSION_NAME}.zip s3://elasticbeanstalk-${{ secrets.AWS_REGION }}-$(aws sts get-caller-identity --query "Account" --output text)/${{ secrets.EB_APP_NAME }}/${VERSION_NAME}.zip
        
        # Create application version
        aws elasticbeanstalk create-application-version \
          --application-name ${{ secrets.EB_APP_NAME }} \
          --version-label ${VERSION_NAME} \
          --source-bundle S3Bucket="elasticbeanstalk-${{ secrets.AWS_REGION }}-$(aws sts get-caller-identity --query "Account" --output text)",S3Key="${{ secrets.EB_APP_NAME }}/${VERSION_NAME}.zip"
        
        # Deploy version
        eb deploy ${{ secrets.EB_ENV_NAME }} --version ${VERSION_NAME}