name: CI/CD Pipeline - Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master  # Replace with the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip python3-dev build-essential
        pip3 install awsebcli

    - name: Initialize Elastic Beanstalk app
      run: |
        eb init -p python-3.11 --region ${{ secrets.AWS_REGION }} --no-verify-ssl NoteCardsApp

    - name: Check if Environment Exists
      run: |
        ENV_EXISTS=$(aws elasticbeanstalk describe-environments --region ${{ secrets.AWS_REGION }} --query "Environments[?EnvironmentName=='${{ secrets.EB_ENV_NAME }}'].EnvironmentName" --output text)
        echo "Environment exists: $ENV_EXISTS"
        if [ "$ENV_EXISTS" == "" ]; then
          echo "Environment doesn't exist. Creating a new environment..."
          eb create ${{ secrets.EB_ENV_NAME }} --region ${{ secrets.AWS_REGION }} --platform python-3.11
        fi

    - name: Package and Deploy
      run: |
        # Create a version name
        VERSION_NAME="app-$(date +'%Y%m%d_%H%M%S')"
        echo "Creating new application version: $VERSION_NAME"
        
        # Zip the app
        zip -r ${VERSION_NAME}.zip .
        
        # Upload it to S3
        aws s3 cp ${VERSION_NAME}.zip s3://elasticbeanstalk-${{ secrets.AWS_REGION }}-859389355576/NoteCards/${VERSION_NAME}.zip
        
        # Create application version in Elastic Beanstalk AFTER uploading the file
        aws elasticbeanstalk create-application-version \
          --application-name NoteCardsApp \
          --version-label ${VERSION_NAME} \
          --source-bundle S3Bucket="elasticbeanstalk-${{ secrets.AWS_REGION }}-859389355576",S3Key="NoteCards/${VERSION_NAME}.zip" \
          --auto-create-application
        
        # Use the specified environment and deploy with the new version
        eb use ${{ secrets.EB_ENV_NAME }}
        eb deploy ${{ secrets.EB_ENV_NAME }} --version ${VERSION_NAME}